description: Runs schedule


inputs:
  token:
    description: github token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@rebase-repo
      with:
        remote_repo: adityak74/google-drive-upload-git-action
        remote_branch: main
