name: Golang with cache
author: Peter Mescalchin
description: Setup requested Golang version with enabled module and build caching.

inputs:
  go-version:
    description: Desired Golang version to use.
  go-version-file:
    description: Path to go.mod file, determines Golang version to use. Used in place of `go-version` input.
  cache-key-suffix:
    description: Optional cache key suffix.
    default:

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: actions/setup-go@master
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
    - name: Determine Golang cache paths
      id: golang-path
      run: |
        echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
        echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
      shell: bash
    - name: Setup Golang cache
      uses: actions/cache@master
      with:
        path: |
          ${{ steps.golang-path.outputs.build }}
          ${{ steps.golang-path.outputs.module }}
        key: ${{ runner.os }}-golang${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}-
